@startuml
title Domain Model - USLP08 (Route Planning)

hide circle
hide methods


class FreightManager
class PendingFreight {
    origin
    destination
    cargoDetails
}

class Route {
    startDate
    startTime
}

class SimpleRoute
class ComplexRoute

class Path {
    stationSequence
}

class Station
class CargoOperation {
    type (Load/Unload)
    quantity
}

' Relacionamentos
FreightManager "1" -- "0..*" Route : defines/assigns >
Route "1" *-- "1" Path : follows >
Path "1" *-- "2..*" Station : consists of >

Route <|-- SimpleRoute
Route <|-- ComplexRoute

SimpleRoute "1" -- "1" PendingFreight : accomplishes >
ComplexRoute "1" -- "1..*" PendingFreight : accomplishes >

Route "1" *-- "1..*" CargoOperation : involves >
CargoOperation "1" -- "1" Station : occurs at >
PendingFreight "1" -- "2" CargoOperation : defines >

@enduml