@startuml
'https://plantuml.com/class-diagram


skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing true

hide methods
hide circles


TrainOperators --> RollingStocks : owns

Trains --> TrainOperators : operated by
Trains --> Routes : follows
Trains --> Wagons : pulls
Trains --> Locomotives : pulls


TrainDriver --> Trains : drives
FreightManager ---> Freight : manages
StationManager --> Stations : oversees

LineSegment --> Sidings : includes

RollingStocks <|-- Locomotives
RollingStocks <|-- Wagons
Freight --> Wagons : transported in

LineSegment --> SingleRailway
LineSegment --> DoubleRailway
RailwayNetwork --> LineSegment : is composed by

Stations --> FreightYards : includes
Stations --> Terminals : includes

RailwayNetwork --> Stations : connects

Planner --> Routes : plans
Routes --> Path : includes
Path --> RailwayNetwork : uses
Path --> Stations : passes through

LineOwners --> LineSegment : owns

Stations --> Buildings : has

Buildings <|-- RefrigeratedAreas
Buildings <|-- GrainSilos
Buildings <|-- Warehouses

Freight --> Stations : delivered to
Freight <-- Stations : picked up from
Freight --> Routes : has assigned

class RailwayNetwork{
totalLength
country
maxSpeed
}

class TrainOperators{
id
name
}

class RollingStocks{
id
type
manufacturer
yearBuilt
status
}
class Trains{
id
}
class Locomotives{
serialNumber
id
make
model
entryYear
type (“diesel”, “electric”)
power
acceleration
fuelCapacity (nullable)
gauge
}
class Wagons{
id
type (“boxcar”, “tank”, “flat”, “hopper”, “refrigerated”)
payloadCapacity
volumeCapacity
tareWeight
gauge
}
class Freight{
id
originStationId
destinationStationId
status
weight
volume
}

class LineSegment{
id
name
gauge
isElectrified (boolean)
totalLength
ownerId
length
maxSpeed
condition
}



class Routes{
id
name
totalDistance
estimatedTime
}
class Path{
id
sequenceNumber
distance
estimatedDuration
}

class SingleRailway{
}
class DoubleRailway{
}



class Stations{
name
location
capacity
openingDate
}
class Buildings{
id
}
class Terminals{
id
type
}
class Trains{
id
model
buildYear
maxSpeed
status
composition
}

class Warehouses{
capacityBoxes
aislesCount
bayCount
}
class RefrigeratedAreas{
}
class GrainSilos{
}

class Planner{
id
name
department
}
class TrainDriver{
id
name
}
class FreightManager{
id
name
}
class StationManager{
id
name
contactNumber
}

class LineOwners{
id
name
}

class FreightYards{
id
area
capacity
typeOfCargo
}
class Sidings{
id
}



@enduml