@startuml


skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber


actor "Warehouse Planner" as Planner
participant ":System" as System

activate Planner

    Planner -> System: generatePickingPlans()
    activate System
        System --> Planner: displayParameterForm()
    deactivate System

    Planner -> System: submitPackingParameters()
    activate System
        System --> Planner: displayPickingPlanResults()
    deactivate System

    Planner -> System: requestTrolleyDetails()
    activate System
        System --> Planner: showTrolleyDetails()
    deactivate System

    Planner -> System: exportPlan(format: "CSV")
    activate System
        System --> Planner: returnFile()
    deactivate System

    Planner -> System: confirmPlanExecution()
    activate System
        System --> Planner: showSuccess("Plano de picking executado com sucesso")
    deactivate System



@enduml