@startuml
'https://plantuml.com/class-diagram


skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing true

hide methods





TrainOperators --> RollingStock : owns

RollingStock --> Trains : is
RollingStock --> Locomotives : is
RollingStock --> Wagons : is
Trains --> Tracks : travel on
Locomotives --> Tracks : travel on
Wagons --> Tracks : travel on





class Tracks{
}

class TrainOperators{
}
class RollingStock{
}
class Trains{
}
class Locomotives{
}
class Wagons{
}



class Bridges{
}
class Tunnels{
}


class Stations{
}
class Terminals{
}

class Warehouses{
}
class RefrigeratedAreas{
}
class GrainSilos{
}





@enduml