@startuml
'https://plantuml.com/class-diagram


skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing true

hide methods
hide circle


TrainOperators --> RollingStocks : owns

Trains --> TrainOperators : operated by
Trains --> Routes : follows
Trains --> Wagons : pulls
Trains --> Locomotives : pulls


TrainDriver --> Trains : drives
FreightManager ---> Freight : manages
StationManager --> Stations : oversees

LineSegment --> Sidings : includes

RollingStocks <|-- Locomotives
RollingStocks <|-- Wagons
Freight --> Wagons : transported in

LineSegment --> SingleRailway
LineSegment --> DoubleRailway
RailwayNetwork --> LineSegment : is composed by

Stations --> FreightYards : includes
Stations --> Terminals : includes

RailwayNetwork --> Stations : connects

Planner --> Routes : plans
Routes --> Path : includes
Path --> RailwayNetwork : uses
Path --> Stations : passes through

LineOwners --> LineSegment : owns

Stations --> Buildings : has

Buildings <|-- RefrigeratedAreas
Buildings <|-- GrainSilos
Buildings <|-- Warehouses

Freight --> Stations : delivered to
Freight <-- Stations : picked up from
Freight --> Routes : has assigned

class RailwayNetwork{
id
name
length
}

class TrainOperators{
id
name
}

class RollingStocks{
}
class Trains{
id
}
class Locomotives{
id
}
class Wagons{
id
}
class Freight{
id
}

class LineSegment{
id
}

class Box{
}
class Order{
}




class Routes{
id
}
class Path{
id
}

class SingleRailway{
}
class DoubleRailway{
}



class Stations{
id
}
class Buildings{
id
}
class Terminals{
id
}


class Warehouses{
}
class RefrigeratedAreas{
}
class GrainSilos{
}

class Planner{
id
name
}
class TrainDriver{
id
name
}
class FreightManager{
id
name
}
class StationManager{
id
name
}

class LineOwners{
id
name
}

class FreightYards{
id
}
class Sidings{
id
}



@enduml