@startuml

title USEI04 - Design Class Diagram

skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam classAttributeIconSize 0

class GetPickingPathUI {
  + requestPath()
}

class GetPickingPathController {
  + getOptimizedPath(plan: PickingPlanDTO)
}

class PickingPlanDTO {
  - bays: List<BayDTO>
  + getBays()
}

class PickingPlanValidator {
  + validate(plan: PickingPlanDTO): boolean
}

class PathSequencingService {
  + calculatePaths(plan: PickingPlan): PickingPath
}

class PickingPlan {
  - planId: String
  - bays: List<Bay>
}

class Bay {
    - aisle: int
    - bay: int
}

class PickingPath {
  - strategyA_Path: List<Bay>
  - strategyA_Distance: double
  - strategyB_Path: List<Bay>
  - strategyB_Distance: double
}

class Repositories {
  + getInstance()
}

class PickingPathRepository {
  + save(path: PickingPath): PickingPath
}


GetPickingPathUI ..> GetPickingPathController : uses
GetPickingPathController ..> PickingPlanDTO : uses
GetPickingPathController ..> PickingPlanValidator : uses
GetPickingPathController ..> PathSequencingService : uses
GetPickingPathController ..> Repositories : uses

PathSequencingService ..> PickingPlan : uses
PathSequencingService ..> PickingPath : creates

Repositories ..> PickingPathRepository : "pathRepository"

PickingPathRepository ..> PickingPath : manages

PickingPlan "1" -- "1..*" Bay : is composed of

@enduml